version: "3"

services:
  api:
    build: api
    container_name: snip-api
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    build: db
    container_name: snip-db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data